### PR TITLE
Very simple support for 7 inch OpenVario with Texim screen

### PR DESCRIPTION
**Pull request by roeles**
This is up to the point where things work. Let's discuss what you prefer to make things pretty.
I also do not know if this eliminates HDMI support. If it does, we'll have to add a switch off course.

### CODE REVIEW

**Comment by hor63** [comment]
Please rename the dts for 7inch Texim panel to a speaking name.
Please add the dts files from the other variants (5 inch Texim, 4 in Ampire, and the 7in Pixel QI) with speaking names.
Let all DTS files be compiled to dtb files and finally copy them all to sdcard/boot.
Please revert the boot.cmd to the original status.

The only switch which needs to be done is in the boot.cmd for U-Boot. I will take care of that.
I will add a selection, but also a job on the target Cubieboard to switch directly on the device.

**Comment by roeles** [comment]
- [x] I will rename the DTS. The way OpenVario does it, is to rename it during copy. Do I understand correctly you want to retain the original filename and switch based on boot.cmd?
- [x] I will add the DTSes, but I cannot confirm if they work. Are all DTSes you mention included here? https://github.com/Openvario/meta-openvario/tree/warrior/recipes-kernel/linux/linux-mainline
- [x] I will copy all DTSes to sdcard/boot

**Questions**
- What do you mean by reverting boot.cmd? I only changed the DTS afaik.

**Comment by hor63** [comment]
> I will add the DTSes, but I cannot confirm if they work. Are all DTSes you mention included here?
> https://github.com/Openvario/meta-openvario/tree/warrior/recipes-kernel/linux/linux-mainline

Yes. These are the ones. For better traceability retain the original names. This makes it easier to keep things in synch.

> What do you mean by reverting boot.cmd? I only changed the DTS afaik.

You changed the echo command in makenewimage.sh which writes boot.cmd. Please revert the content there.
Also where you replaced the original dts and dtb in the script please re-instate the original and _add_ the new DTS and DTB files

**Comment by roeles** [comment]
When looking at 4.3 inch support, I see this DTS file:
https://raw.githubusercontent.com/Openvario/meta-openvario/warrior/recipes-kernel/linux/linux-mainline/openvario-43-rgb.dts

This doesn't look functional. Do you still want it included?

**Comment by roeles** [comment]
I'm closing this PR in favor of a new one.

**Pull request closed without merging**
